package com.clout.cron.batch;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Properties;

import org.apache.log4j.Logger;
import org.springframework.batch.core.BatchStatus;
import org.springframework.batch.core.Job;
import org.springframework.batch.core.JobExecution;
import org.springframework.batch.core.JobParametersBuilder;
import org.springframework.batch.core.launch.JobLauncher;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.jdbc.core.JdbcTemplate;

import com.clout.cron.batch.jobitems.JobState;
import com.clout.cron.batch.jobs.yellowpages.LoadLinkByCityStateService;
import com.clout.cron.batch.mapper.DataProcessingCronsMapper;
import com.clout.cron.batch.model.DataProcessingCrons;
import com.clout.cron.batch.model.KeyValuePair;

public class OtherJobs implements BatchJob {
	private final static Logger logger = Logger.getLogger(OtherJobs.class);

	private String[] args;
	
	public OtherJobs() {}
	
	public OtherJobs(String[] args) {
		this.args = args;
	}
	
	@Override
	public void execute() throws CronJobException {
		String[] springConfig  = 
			{	
				"spring/batch/jobs/common-context.xml",
				"spring/batch/database.xml"
			};
		

		/*
		 * argument 2
		 *   spring/batch/jobs/staticmap.xml
		 *   spring/batch/jobs/crawler-sitemap.xml
		 */
		
		if(args.length < 3) {
			logger.error("The job name provided does not exist.  Job is missing parameters.");
			logger.info("Exit Code 1");
			System.exit(1);
		}
		

		ClassPathXmlApplicationContext context =  new ClassPathXmlApplicationContext("spring/batch/jobs/common-context.xml", "spring/batch/database.xml", args[1]);

		logger.info("args " + args[0] + " " + args[1] + " " + args[2]);
		 
		String jobName = args[0];

		String propertiesFile = args[2];
		
		Properties props = new Properties();
		
		try {
			props.load(new FileInputStream(propertiesFile));
		} catch (IOException e2) {
			logger.error("Error loading properties file");
			System.exit(1);
		}

		
		JdbcTemplate jdbcTemplate = (JdbcTemplate) context.getBean("localJdbcTemplate");
		JobState jobState = (JobState) context.getBean("jobState");
		
		
		try {

			/**
			 * ************
			 * DOING ONE OFF JOB
			 */
			if("generateLinksJob".equals(jobName)) {
				String city = args[3].split("=")[1];
				String state = args[4].split("=")[1];
				String[] categories = args[5].split("=")[1].split(",");
				
				LoadLinkByCityStateService loadLinkByCityStateService = (LoadLinkByCityStateService) context.getBean("loadLinkByCityService");				
				loadLinkByCityStateService.load(city, state, categories);
				System.exit(0);
			}
			
			if("yelpLinksJob".equals(jobName)) {
				String city = args[3].split("=")[1];
				String state = args[4].split("=")[1];
				String[] categories = args[5].split("=")[1].split(",");
				
				LoadLinkByCityStateService loadLinkByCityStateService = (LoadLinkByCityStateService) context.getBean("loadLinkByCityService");				
				loadLinkByCityStateService.load(city, state, categories);
				System.exit(0);
			}
			
			
			/**
			 * ************
			 * DOING ONE OFF JOB
			 */
			
			if("simpleYellowpagesJob".equals(jobName)) {
				String city = args[3].split("=")[1];
				String state = args[4].split("=")[1];
				
				String[] categories = new String[] {"AMUSEMENT & THEME PARKS","ARCADES & AMUSEMENTS","ART GALLERIES & DEALERS","ART RESTORATION & CONSERVATION","ART SCHOOLS","ART SUPPLIES RETAIL","ARTISTS & ART STUDIOS","ARTS ORGANIZATIONS & INFORMATION","BALLROOMS","CULTURAL ATTRACTIONS EVENTS & FACILITIES","DANCE COMPANIES","DANCE INSTRUCTORS","DANCE STUDIOS","ENTERTAINERS","ENTERTAINMENT AGENCIES & BUREAUS","EVENT PLANNING","FINE ART ARTISTS","FIREWORKS","INSTRUMENTAL MUSIC INSTRUCTION","LIBRARIES","LIVE THEATER","MODELING AGENCIES","MOTION PICTURE PRODUCERS & STUDIOS","MOTION PICTURE PRODUCTION SERVICES & FACILITIES","MOVIE THEATERS","MUSEUMS","MUSIC PUBLISHERS","MUSIC STORES","MUSICIANS","NEWS DEALERS & NEWSSTANDS","NEWSPAPER PUBLISHERS","ORCHESTRAS SYMPHONIES & BANDS","PARTY DECORATIONS RETAIL","PERFORMING ARTS SCHOOLS","PHOTOGRAPHY","PORTRAIT STUDIOS","PUBLIC LIBRARIES","RADIO STATIONS","RECORD LABELS","RECORDING STUDIOS","TELEVISION & RADIO ADVERTISING PRODUCTION","TELEVISION ADVERTISING","TELEVISION PROGRAM PRODUCERS & DISTRIBUTORS","TELEVISION STATIONS","THEATRICAL MANAGERS & PRODUCERS","USED RARE & OUT OF PRINT BOOKS","VIDEO PRODUCTION SERVICES","VIDEO PRODUCTION SERVICES COMMERCIAL","VIDEOTAPE EDITING","YARN","ANTIQUE & CLASSIC AUTO DEALERS","ANTIQUE & CLASSIC AUTO RESTORATION & REPAIR","AUTO & TRUCK BROKERS","AUTO & TRUCK WRECKING","AUTO ACCESSORIES RETAIL","AUTO AIR CONDITIONING & HEATING","AUTO AIR CONDITIONING & HEATING SERVICE & REPAIR","AUTO ALARMS & SECURITY SYSTEMS","AUTO ALIGNMENT FRAMES & AXLES SERVICE & REPAIR","AUTO ALTERNATORS & STARTERS","AUTO AUCTIONS","AUTO BATTERIES","AUTO BODY EQUIPMENT & SUPPLIES RETAIL","AUTO BODY REPAIR & PAINTING","AUTO BUYERS","AUTO CLEANING & DETAILING","AUTO CUSTOMIZING CONVERSION & RESTORATION","AUTO DEALERS","AUTO DIAGNOSTIC SERVICES","AUTO ELECTRICAL SYSTEMS SERVICE & REPAIR","AUTO EMISSIONS TESTING & REPAIR","AUTO ENGINE REBUILDING","AUTO ENGINES SERVICE & REPAIR","AUTO EQUIPMENT & SUPPLIES WHOLESALE & MANUFACTURERS","AUTO GLASS COATING & TINTING","AUTO GLASS REPLACEMENT & REPAIR","AUTO GLASS RETAIL","AUTO INSPECTION","AUTO LEASING","AUTO LICENSES","AUTO LOCKS & LOCKOUT SERVICES","AUTO MACHINE SHOP SERVICES","AUTO OIL & LUBE","AUTO PAINT","AUTO PARTS RETAIL","AUTO PARTS WHOLESALE & MANUFACTURERS","AUTO PERFORMANCE & RACING EQUIPMENT & SUPPLIES","AUTO RACING","AUTO RADIATOR REPAIR & REBUILDING","AUTO RADIATORS RETAIL","AUTO RECYCLING & DISMANTLING","AUTO REGISTRATION TAGS & TITLES","AUTO RENTAL","AUTO SALVAGE YARDS","AUTO SERVICE & REPAIR","AUTO TIRE SHOP EQUIPMENT & SUPPLIES","AUTO TRAILER DEALERS","AUTO TRANSMISSIONS","AUTO TRANSPORT","AUTO TUNE UPS","AUTO UPHOLSTERY RETAIL","AUTO WARRANTY SERVICES","AUTO WASHING & POLISHING","BRAKES SERVICE & REPAIR","CAR STORAGE","CARS SERVICE & REPAIR","COLLISION SERVICES","COMMERCIAL AUTO RENTAL","CUSTOM AUTO PAINTING","CUSTOM CAR PARTS & ACCESSORIES","DIESEL ENGINE PARTS SALES & SERVICE","DIESEL FUEL","DIESEL FUEL INJECTION SERVICE SALES & PARTS","DRIVING SCHOOLS","ELECTRIC MOTOR DEALERS","ELECTRIC VEHICLES","ENGINES REBUILDING SERVICE & REPAIR","EXOTIC & LUXURY CAR RENTAL & LEASING","GAS STATIONS","MOTORCYCLE & MOTOR SCOOTER PAINTING & CUSTOMIZING","MOTORCYCLE INSURANCE","MOTORCYCLES MOTOR SCOOTERS & ATVS SERVICE & REPAIR","MUFFLERS & EXHAUST SYSTEMS RETAIL","MUFFLERS & EXHAUST SYSTEMS SERVICE & REPAIR","PARKING","PARKING FACILITIES","PARKING GARAGES","PARKING SERVICES","PROPANE GAS REFILLING STATIONS","RACE CAR DEALERS","ROADSIDE ASSISTANCE","RV & CAMPER DEALERS","RV & CAMPER STORAGE","RVS & CAMPERS SERVICE & REPAIR","SERVICE STATIONS","SMALL ENGINES REPAIR","TIRES RETAIL","TOWING","TRAILER EQUIPMENT & PARTS RETAIL","TRAILER HITCHES RETAIL","TRAILERS SERVICE & REPAIR","TRUCK BODY REPAIR & PAINTING","TRUCK CAPS & TONNEAU COVERS RETAIL","TRUCK DEALERS","TRUCK EQUIPMENT PARTS & ACCESSORIES RETAIL","TRUCK LEASING","TRUCK RENTAL","TRUCK STOPS","TRUCK STRIPING & LETTERING","TRUCK TIRES","TRUCK TRAILER RENTAL & LEASING","TRUCK WASHING & CLEANING","USED & PRE-OWNED CARS","USED & REBUILT AUTO PARTS RETAIL","USED & REBUILT AUTO PARTS WHOLESALE & MANUFACTURERS","USED & REBUILT TIRES","USED CARS WHOLESALE","USED TRUCKS","VAN DEALERS","VAN RENTAL","WHEELS & TIRES SERVICE & REPAIR","WHEELS & WHEEL COVERS RETAIL","ADVERTISING","ADVERTISING & DESIGN AGENCIES","ADVERTISING & PROMOTIONAL GIFTS","ADVERTISING & PROMOTIONAL PRODUCT DEALERS","ADVERTISING AGENCIES & CONSULTANTS","ADVERTISING DISTRIBUTION SERVICES","ADVERTISING SPECIALTIES WHOLESALE & MANUFACTURERS","AERIAL APPLICATORS","AERIAL PHOTOGRAPHERS","AIR DUCT CLEANING","ANSWERING SERVICES","ARCHIVES RECORDS & DOCUMENTS STORAGE","ARMORED CAR SERVICES","ASSOCIATION MANAGEMENT CONSULTANTS","AUDIOVISUAL CONSULTANTS & DESIGNERS","BEER & ALE DISTRIBUTORS","BILLING SERVICES","BIOTECHNOLOGY PRODUCTS & SUPPLIES","BLUEPRINTING","BOILER CLEANING & REPAIR","BOOK PUBLISHERS","BOOKBINDING","BROKERS CONSULTANTS","BUSINESS & PROFESSIONAL ASSOCIATIONS & ORGANIZATIONS","BUSINESS ANSWERING SERVICES","BUSINESS BROKERS","BUSINESS CELL PHONE EQUIPMENT & SUPPLIES","BUSINESS CONSULTANTS & ADVISORS","BUSINESS DEVELOPMENT","BUSINESS FORM & CARD PRINTING","BUSINESS FORMS & SYSTEMS","BUSINESS INFORMATION","BUSINESS MANAGEMENT SERVICES","BUSINESS RECORDS STORAGE & MANAGEMENT","BUSINESS SERVICES","CARPET RUG & UPHOLSTERY CLEANING COMMERCIAL & INDUSTRIAL","CHECK CASHING SERVICES","CIVIL ENGINEERS","CLOSED CIRCUIT TELEVISION EQUIPMENT & SECURITY SYSTEMS","COMMERCIAL & GRAPHIC ARTISTS","COMMERCIAL & GRAPHIC ARTS","COMMERCIAL PRINTING","COMMERCIAL SIGNS","COMMUNICATIONS & PUBLIC RELATIONS CONSULTANTS","COMMUNICATIONS SERVICES","CONCESSION STANDS","CONVEYORS & CONVEYING EQUIPMENT","COPIERS & SUPPLIES","COPIERS SERVICE & REPAIR","COPYING & DUPLICATING SERVICES","CORPORATE ADVERTISING SPECIALTIES & PROMOTIONS","DESIGN","DESIGNERS","DESIGNERS COMMERCIAL & INDUSTRIAL","DESKTOP PUBLISHING","DETECTIVE AGENCIES","DIRECT MAIL ADVERTISING SERVICES","DIRECT MARKETING","DIRECTORY & GUIDE ADVERTISING","DIRECTORY & GUIDE PUBLISHERS","DISPLAY DESIGNERS & PRODUCERS","ECONOMIC RESEARCH ANALYSIS & DEVELOPMENT","EMPLOYEE BENEFIT & COMPENSATION PLANS","EMPLOYMENT","EMPLOYMENT AGENCIES","EMPLOYMENT BACKGROUND CHECKS","EMPLOYMENT CONSULTANTS","EMPLOYMENT OPPORTUNITIES","EMPLOYMENT SCREENING SERVICES","EMPLOYMENT TRAINING SERVICES","ENERGY & ENVIRONMENT","ENGINEERING SERVICES","ENGINEERS","ENVIRONMENTAL & ECOLOGICAL CONSULTANTS","ENVIRONMENTAL ENGINEERS","ENVIRONMENTAL SERVICES","ETCHING & ENGRAVING","EVENTS PHOTOGRAPHERS","EXECUTIVE SEARCH FIRMS","FACILITIES MANAGEMENT","FASHION DESIGNERS","FAX SERVICES","FAX SOFTWARE EQUIPMENT & SUPPLIES","FILING EQUIPMENT SYSTEMS & SUPPLIES","FIRE EXTINGUISHERS","FIRE PROTECTION CONSULTANTS","FIRE PROTECTION EQUIPMENT SYSTEMS & SERVICES","FIRE SPRINKLER SYSTEMS","FLORAL & BALLOON ARRANGEMENTS","FOOD SERVICE CONSULTANTS","FUNDRAISING","FUNDRAISING CONSULTANTS & ORGANIZATIONS","GOURMET COFFEE","GRAPHICS SERVICES","GREASE COLLECTION SERVICES","HOTEL & MOTEL MANAGEMENT","HUMAN RELATIONS CONSULTANTS","HUMAN RESOURCE CONSULTANTS","HYDRAULIC EQUIPMENT & SUPPLIES SERVICE & REPAIR","INFORMATION BUREAUS & SERVICES","INFORMATION SYSTEMS CONSULTANTS","INTERIOR DECORATORS & DESIGNERS","INTERNATIONAL BUSINESS SERVICES","INVENTORY SERVICES","INVESTIGATION SERVICES","JANITORIAL SERVICES","JEWELRY DESIGNERS","KEYS","LABORATORIES","LAND PLANNING","LAND SURVEYORS","LINEN SUPPLY SERVICES","LOBBYISTS","LOCKS & LOCKSMITHS COMMERCIAL & INDUSTRIAL","LOCKSMITH REFERRAL SERVICES","MAGAZINE & JOURNAL PUBLISHERS","MAILBOX RENTAL","MAJOR APPLIANCES SERVICE & REPAIR","MANAGEMENT CONSULTANTS","MANUFACTURERS\" AGENTS & REPRESENTATIVES","MANUFACTURING ENGINEERS","MARINE UPHOLSTERY","MARKET RESEARCH","MARKETING & PUBLIC RELATIONS","MARKETING CONSULTANTS","MARKETING PROGRAMS & SERVICES","MARKETING SALES","MECHANICAL ENGINEERS","MEDICAL TRANSCRIPTION","MERCHANDISE BROKERS","METAL RECYCLING","MONUMENTS & MARKERS DEALERS","MOVING BOXES","MULTIMEDIA","MUSICAL INSTRUMENTS SERVICE & REPAIR","NOTARIES PUBLIC","OFFICE BUILDING & INDUSTRIAL CLEANING SERVICES","OFFICE FURNITURE & EQUIPMENT DEALERS","OFFICE FURNITURE & EQUIPMENT REFINISHING & REPAIR","OFFICE FURNITURE & EQUIPMENT RENTAL & LEASING","OUTDOOR ADVERTISING & BILLBOARDS","PACKAGING MACHINERY RETAIL","PAPER SHREDDING SERVICES","PARTY EQUIPMENT & SUPPLIES SALES & RENTAL","PARTY PLANNING","PARTY SERVICES","PERSONAL TRANSCRIBING SERVICES","PEST CONTROL SERVICES COMMERCIAL & INDUSTRIAL","PHOTO FILM DEVELOPING","PHOTO RETOUCHING & COLORING","PHYSICAL & BIOLOGICAL RESEARCH COMMERCIAL","PIANO TUNING REPAIR & REFINISHING","PORTRAIT & COMMERCIAL PHOTOGRAPHY","PORTRAIT PHOTOGRAPHERS","POWER SWEEPERS & SCRUBBERS","PRESSURE CLEANING","PRINT BROKERS","PRINTERS\" SUPPORT SERVICES","PRINTING DESIGN SERVICES","PRINTING EQUIPMENT & SUPPLIES DEALERS","PRINTING SERVICES","PRIVATE DETECTIVES","PRIVATE INVESTIGATORS","PRODUCT DEVELOPMENT & MARKETING","PROFESSIONAL & TRADE ASSOCIATIONS","PROFESSIONAL ENGINEERS","PROFESSIONAL PHOTOGRAPHERS","PROTECTIVE COATINGS","PUBLISHERS","PUBLISHING CONSULTANTS & SERVICES","PUMPS PARTS & SUPPLIES DEALERS","RADIO SALES & SERVICE","RECORDS MANAGEMENT","RECRUITMENT & STAFFING SERVICES","RECYCLING CENTERS","RECYCLING SERVICES EQUIPMENT & SUPPLIES","RELOCATION SERVICES","RENTAL MANAGEMENT SERVICES","REPOSSESSION SERVICES","RESEARCH & DEVELOPMENT SERVICES","RESTAURANT EQUIPMENT SERVICE & REPAIR","RESTAURANT MANAGEMENT & CONSULTANTS","RESUME SERVICES","SAFES & VAULTS OPENING & REPAIRING","SALES ORGANIZATIONS","SALES PROMOTIONS & COUNSELING SERVICES","SANITARY LANDFILLS","SANITATION CONSULTANTS & SERVICES","SATELLITE EQUIPMENT & SYSTEM DEALERS","SAW SALES SHARPENING & REPAIR","SCALES RETAIL","SCRAP IRON & METALS","SCRAPBOOKING","SCREEN PRINTING","SECRETARIAL SERVICES","SECURITY CONSULTANTS & AGENCIES","SECURITY GUARD & PATROL SERVICES","SECURITY SYSTEMS & SERVICES","SEWING CONTRACTORS","SEWING MACHINES SERVICE & REPAIR","SHARPENING SERVICES","SHEET METAL WORK","SIGN DEALERS","SIGN INSTALLATION & HANGING","SNOW REMOVAL & SANDING","STAFF LEASING SERVICES","STORE FRONTS & SUPPLIES","STRUCTURAL ENGINEERS","SURVEILLANCE EQUIPMENT & SERVICES","SURVEYING SERVICES","TALENT AGENCIES & CASTING SERVICES","TAXIDERMISTS","TELECOMMUNICATIONS CONSULTANTS","TELEMARKETING SERVICES","TEMPORARY EMPLOYMENT AGENCIES","TRANSLATORS & INTERPRETERS","TREE SERVICES COMMERCIAL & INDUSTRIAL","TYPING & WORD PROCESSING SERVICES","URBAN & REGIONAL PLANNERS","UTILITIES","VACUUM CLEANERS SERVICE & REPAIR COMMERCIAL & INDUSTRIAL","VENDING MACHINES","VIDEOTAPE CD & DVD DUPLICATION & TRANSFER SERVICES","WASTE MANAGEMENT","WATER EXTRACTION & DAMAGE RESTORATION","WATER TREATMENT SERVICE EQUIPMENT & SUPPLIES","WATER UTILITY COMPANIES","WEDDING PHOTOGRAPHY & VIDEOS","WEDDING SERVICES","WELDING SERVICES","WIRELESS COMMUNICATIONS","WRITING CONSULTANTS","ALTERATIONS & TAILORING","BOOTS & SAFETY SHOES","BOOTS & SHOES REPAIR","BOUTIQUES","BRIDAL & EVENING SHOES","BRIDAL SHOPS & SERVICES","BRIDAL SUPPLIES","CHILDREN\"S & INFANTS\" ACCESSORIES","CHILDREN\"S & INFANTS\" CLOTHING RETAIL","CLOTHING & ACCESSORIES CONSIGNMENT & RESALE","CLOTHING ACCESSORIES RETAIL","CLOTHING STORES","COSTUME SALES & RENTAL","DANCE CLOTHING","DIAMONDS RETAIL","DRESSMAKERS","EMBROIDERY & NEEDLEWORK","EMBROIDERY SERVICE","FORMAL WEAR SALES & RENTAL","JEWELRY BROKERS & BUYERS","JEWELRY REPAIR","JEWELRY WHOLESALE & MANUFACTURERS","KNITTING & CROCHETING ACCESSORIES & SUPPLIES","LAUNDRIES","LEATHER CLOTHING CLEANING & REPAIR","LEATHER CLOTHING RETAIL","MASQUERADE & THEATRICAL COSTUMES SALES & RENTAL","MATERNITY CLOTHING & ACCESSORIES RETAIL","MEN\"S ACCESSORIES RETAIL","MEN\"S CLOTHING RETAIL","SAFETY CLOTHING & EQUIPMENT","SHOE STORES","SPORTSWEAR RETAIL","SWIMWEAR RETAIL","TAILORS","T-SHIRTS RETAIL","UNIFORM RENTAL & CLEANING SERVICE","UNIFORMS COMMERCIAL & INDUSTRIAL","UNIFORMS RETAIL","USED CLOTHING RETAIL","WATCHES RETAIL","WATCHES SERVICE & REPAIR","WESTERN CLOTHING RETAIL","WOMEN\"S ACCESSORIES RETAIL","WOMEN\"S CLOTHING","WOMEN\"S SHOES","WOMEN\"S UNDERWEAR & LINGERIE RETAIL","ADOPTION AGENCIES & SERVICES","ADULT CARE","ADULT DAY CARE CENTERS","ADVENTIST CHURCHES","AMBULANCE SERVICES","ANIMAL RESCUE & RELOCATION SERVICES","APOSTOLIC CHURCHES","ASSEMBLY OF GOD CHURCHES","BANQUET FACILITIES","BAPTIST CHURCHES","BIBLES & RELIGIOUS BOOKS","CATHOLIC CHURCHES","CHAMBERS OF COMMERCE","CHARITABLE & NONPROFIT ORGANIZATIONS","CHARITABLE EDUCATIONAL & RESEARCH FOUNDATIONS","CHILD & ADOLESCENT GUIDANCE COUNSELING","CHILD CARE AGENCIES","CHILD CARE CENTERS","CHILD CARE CONSULTANTS","CHRISTIAN CHURCHES","CHRISTIAN MINISTRIES","CHURCH & RELIGIOUS ASSOCIATIONS & ORGANIZATIONS","CHURCH OF CHRIST CHURCHES","CHURCH OF GOD CHURCHES","CHURCH OF JESUS CHRIST OF LATTER DAY SAINTS CHURCHES","CHURCH OF THE NAZARENE CHURCHES","CHURCH SUPPLIES","CHURCHES","CIVIC CLUBS & ORGANIZATIONS","CIVIL DEFENSE AGENCIES","CLERGY","CLERGY & PASTORAL COUNSELORS","COMMUNITY & CIVIC ORGANIZATIONS","COMMUNITY CENTERS","COMMUNITY SERVICES","CONGRESSIONAL REPRESENTATIVES","CONSULATES","CONSUMER ORGANIZATIONS & COOPERATIVES","CONVENTION & MEETING FACILITIES & SERVICES","CONVENTION VISITORS & INFORMATION CENTERS","CONVENTIONS CONFERENCES & TRADE SHOWS","CONVENTS & MONASTERIES","CORRECTIONAL INSTITUTIONS","COUNSELING CENTERS","COUNSELING SERVICES","COUNTY GOVERNMENT OFFICES","COURTS","DATING & INTRODUCTION SERVICES","EASTERN ORTHODOX CHURCHES","ECONOMIC DEVELOPMENT","ENVIRONMENTAL ORGANIZATIONS","EPISCOPAL CHURCHES","FEDERAL GOVERNMENT OFFICES","FIRE & WATER DAMAGE CLEANING & RESTORATION","FIRE DEPARTMENTS","FOSTER CARE SERVICES","FRATERNAL ORGANIZATIONS","FRATERNITIES & SORORITIES","GOVERNMENT CONTRACTORS","GOVERNMENT OFFICES","HISTORICAL PLACES & SERVICES","HOMELESS SERVICES","HOUSING & ECONOMIC DEVELOPMENT","HOUSING ASSISTANCE","HOUSING AUTHORITIES","HOUSING PROJECTS","INDIVIDUAL & FAMILY SERVICES ORGANIZATIONS","INDIVIDUAL COUNSELING","INTERDENOMINATIONAL CHURCHES","JEHOVAH\"S WITNESS CHURCHES","JEWISH SYNAGOGUES","LABOR ORGANIZATIONS","LOCAL GOVERNMENT OFFICES","LUTHERAN CHURCHES","MARRIAGE & FAMILY COUNSELING INFORMATION & REFERRAL SERVICES","METHODIST CHURCHES","MILITARY & VETERANS ORGANIZATIONS","MILITARY RECRUITING","MINISTRIES CHURCHES","MISSION CHURCHES","MUNICIPAL COURTS","NATIONAL SECURITY","NATIVE AMERICAN GOVERNMENT OFFICES","NON-DENOMINATIONAL CHURCHES","PENTECOSTAL CHURCHES","PERSONS WITH DISABILITIES ORGANIZATIONS","POLICE DEPARTMENTS","POLITICAL ORGANIZATIONS","POST OFFICES","PRESBYTERIAN CHURCHES","PROBATION SERVICES","PSYCHICS & MEDIUMS","PUBLIC HEALTH & SAFETY","RELIGIOUS GOODS STORES","RESIDENTIAL CARE FACILITIES","RETIREMENT & LIFE CARE CENTERS","REVERENDS","SCIENCE OF MIND CHURCHES","SENIOR CITIZENS\" CENTERS & ORGANIZATIONS","SENIOR CITIZENS\" PRODUCTS & SERVICES","SEVENTH DAY ADVENTIST CHURCHES","SHELTERS","SHERIFF\"S DEPARTMENT","SOCIAL & HUMAN SERVICES ORGANIZATIONS","SOCIAL SECURITY COUNSELORS & REPRESENTATIVES","SOCIAL WORKERS","SPECIAL INTEREST LIBRARIES","STATE GOVERNMENT OFFICES","STATE HIGHWAY PATROL","SYNAGOGUES & TEMPLES","UNITED CHURCH OF CHRIST CHURCHES","UNITED METHODIST CHURCHES","URGENT CARE CENTERS","WOMEN\"S ORGANIZATIONS","YOUTH ORGANIZATIONS CENTERS & CLUBS","AUDIOVISUAL EQUIPMENT PARTS & SUPPLIES DEALERS","AUDIOVISUAL EQUIPMENT RENTAL & LEASING","AUDIOVISUAL EQUIPMENT SERVICE & REPAIR","AUDIOVISUAL EQUIPMENT WHOLESALE & MANUFACTURERS","AUDIOVISUAL PRODUCTION SERVICES","CAMERAS & CAMERA SUPPLIES","CAR AUDIO & VIDEO RETAIL","CELL PHONE DEALERS","CELL PHONE EQUIPMENT & SUPPLIES","CELL PHONE REPAIR & INSTALLATION","CELL PHONE SERVICES","CELL PHONES","COMPUTER & EQUIPMENT DEALERS","COMPUTER & SOFTWARE STORES","COMPUTER & SOFTWARE TECHNICAL SUPPORT","COMPUTER AIDED DESIGN SERVICES","COMPUTER CABLE & WIRE INSTALLATION","COMPUTER CONSULTANTS","COMPUTER GRAPHICS & IMAGING","COMPUTER NETWORK HARDWARE","COMPUTER NETWORKS","COMPUTER SOFTWARE","COMPUTER SOFTWARE WHOLESALE & MANUFACTURERS","COMPUTER SUPPLIES PARTS & ACCESSORIES","COMPUTER SYSTEMS CONSULTANTS & DESIGNERS","COMPUTER SYSTEMS INTEGRATION","COMPUTERS & EQUIPMENT RENTAL & LEASING","COMPUTERS & EQUIPMENT REPAIR & MAINTENANCE","COMPUTERS & EQUIPMENT WHOLESALE & MANUFACTURERS","DATA COMMUNICATIONS CABLING","DATA COMMUNICATIONS EQUIPMENT & SYSTEMS","DATA COMMUNICATIONS SERVICE & REPAIR","DATA PROCESSING SERVICES","DATA RECOVERY","DATA SYSTEMS CONSULTANTS & DESIGNERS","DIGITAL IMAGING","ELECTRIC & ELECTRONIC EQUIPMENT & SUPPLIES","ELECTRICAL ENGINEERS","ELECTRONIC COMPONENTS","ELECTRONIC EQUIPMENT & SUPPLIES RETAIL","ELECTRONIC EQUIPMENT & SUPPLIES SERVICE & REPAIR","ELECTRONIC RESEARCH DESIGN & DEVELOPMENT","ELECTRONICS","ELECTRONICS CONSULTANTS","HELP DESK SERVICES","HOME THEATERS & ENTERTAINMENT CENTERS","INFORMATION TECHNOLOGY SERVICES","INTERNET ADVERTISING","INTERNET MARKETING SERVICES","INTERNET PRODUCTS & SERVICES","INTERNET SERVICE PROVIDERS","INTERNET SERVICES","LOCAL PHONE SERVICES","NON-CELLULAR MOBILE PHONE SERVICE","PAGER & BEEPER SALES & SERVICE","PHONE COMMUNICATIONS SERVICES","PHONE EQUIPMENT & SYSTEMS DEALERS","PHONE EQUIPMENT & SYSTEMS PARTS & SUPPLIES","PHONE EQUIPMENT & SYSTEMS SERVICE & REPAIR","PRINTING EQUIPMENT SERVICE & REPAIR","RADIO COMMUNICATION SYSTEMS & SERVICES","RADIO PHONE EQUIPMENT & SYSTEMS","SATELLITE EQUIPMENT & SYSTEMS SERVICE & REPAIR","SATELLITE TELEVISION SERVICES","SCANNING SERVICES","SOFTWARE DESIGN & DEVELOPMENT","SOUND EQUIPMENT & SYSTEMS SALES RENTAL & LEASING","STEREO EQUIPMENT DEALERS","TELECOMMUNICATIONS EQUIPMENT","TELECOMMUNICATIONS SERVICES","TELEVISION RENTAL & LEASING","TELEVISIONS RETAIL","TELEVISIONS SERVICE & REPAIR","USED & RECYCLED COMPUTERS","WEB SITE DEVELOPERS","WEB SITE HOSTING","WEB SITES","ABRASIVES & ABRASIVE PRODUCTS","ACOUSTICAL CONTRACTORS","AIR CONDITIONING CONTRACTORS","AIR CONDITIONING PARTS & SUPPLIES DEALERS","AIR CONDITIONING SERVICE & REPAIR","ARCHITECTS","ARCHITECTURAL DESIGNERS","ARCHITECTURAL SERVICES","ASBESTOS & LEAD ABATEMENT & REMOVAL SERVICES","ASPHALT & ASPHALT PRODUCTS","ASPHALT PAVING CONTRACTORS","BACKFLOW DEVICE INSTALLATION TESTING & SERVICE","BASEMENT REPAIR & RESTORATION","BATHROOM & KITCHEN CONTRACTORS","BATHROOM FIXTURES & ACCESSORIES RETAIL","BATHROOM PLANNING & REMODELING","BRICKLAYERS","BUILDERS & CONTRACTORS","BUILDING & HOME CONSTRUCTION","BUILDING CONSTRUCTION & DESIGN CONSULTANTS","BUILDING MAINTENANCE","BUILDING MATERIALS & SUPPLIES DEALERS","BUILDING REMODELING & REPAIR CONTRACTORS","BUILDING RESTORATION & PRESERVATION","CABINET DEALERS","CABINET REFACING REFINISHING & RESURFACING","CABINETS & CABINET MAKERS RESIDENTIAL","CARPENTERS","CEILING CONTRACTORS","CERAMIC TILE CONTRACTORS","CERAMIC TILE INSTALLATION & REPAIR","CERAMIC TILES","CLOSET SYSTEMS & ORGANIZERS","COMMERCIAL & INDUSTRIAL BUILDING CONTRACTORS","CONCRETE & CONCRETE PRODUCTS DEALERS","CONCRETE BLOCKS & SHAPES","CONCRETE BREAKING CORING CUTTING DRILLING & SAWING","CONCRETE CONTRACTORS","CONCRETE PUMPING SERVICE & EQUIPMENT","CONCRETE REPAIR & RESTORATION CONTRACTORS","CONSTRUCTION CLEAN UP CONTRACTORS","CONSTRUCTION COMPANIES","CONSTRUCTION CONSULTING & MANAGEMENT SERVICES","CONSTRUCTION ENGINEERS","CONSTRUCTION ESTIMATORS","CONSULTING ENGINEERS","CONTRACTORS\" EQUIPMENT & SUPPLIES DEALERS","CONTRACTORS\" EQUIPMENT & SUPPLIES RENTAL & LEASING","CONTROL SYSTEMS & REGULATORS DEALERS","COUNTERTOPS & SINK TOPS","CRANES HOISTING & RIGGING SERVICES","CRUSHED STONE","DECK DESIGNERS & BUILDERS","DOCK BUILDERS & SERVICES","DOOR & DOOR FRAME DEALERS","DOOR & WINDOW DEALERS","DOOR & WINDOW SCREEN SALES & REPAIR","DOOR GLASS & MIRRORS","DOOR REPAIR","DOORS & WINDOWS INSTALLATION","DRAFTING SERVICES","DRIVEWAY CONTRACTORS & CONSTRUCTION","DRYWALL CONTRACTORS","DRYWALL EQUIPMENT & SUPPLIES","DUMP TRUCKING","ELECTRIC CONTRACTORS","ELECTRIC CONTRACTORS COMMERCIAL & INDUSTRIAL","ELECTRIC CONTRACTORS RESIDENTIAL","ELECTRIC EQUIPMENT & SUPPLIES DEALERS","ELECTRIC EQUIPMENT & SUPPLIES JOB LOTS","ELECTRIC EQUIPMENT & SUPPLIES WHOLESALE & MANUFACTURERS","ELEVATOR DEALERS","ELEVATOR INSTALLATION TESTING & REPAIR","ENERGY CONSERVATION PRODUCTS & SERVICES","ENERGY MANAGEMENT & CONSERVATION CONSULTANTS","ENERGY MANAGEMENT SYSTEMS & PRODUCTS","EXCAVATING & DITCHING EQUIPMENT","EXCAVATION CONTRACTORS","FASTENERS","FENCE CONTRACTORS & BUILDERS","FENCE DEALERS","FENCE MATERIALS","FIRE & WATER DAMAGE RESTORATION COMMERCIAL & INDUSTRIAL","FIRE SPRINKLER SYSTEMS RESIDENTIAL","FLOOD CLEANUP","FLOOR INSTALLATION & REFINISHING COMMERCIAL & INDUSTRIAL","FLOOR RESURFACING MATERIALS","FLOORS & FLOORING CONTRACTORS","FLOORS & FLOORING INSTALLATION & REFINISHING","FLOORS & FLOORING WHOLESALE & MANUFACTURERS","FOUNDATION CONTRACTORS","FOUNDATION DRILLING & BORING CONTRACTORS","FURNACE CLEANING & REPAIR","GARAGE BUILDERS","GARBAGE CONTAINERS & DUMPSTERS","GARBAGE REMOVAL CONTRACTORS\" EQUIPMENT & SUPPLIES","GENERATOR DEALERS","GEOLOGISTS","GEOTECHNICAL ENGINEERS","GEOTHERMAL HEATING & COOLING","GLASS & GLASS PRODUCTS DEALERS","GLASS REPLACEMENT & REPAIR","GRADING CONTRACTORS","GRANITE & MARBLE DEALERS","GRANITE DEALERS","HAND & POWER TOOLS","HARDWOOD","HEAT PUMP DEALERS","HEATING & AIR CONDITIONING CONTRACTORS","HEATING & AIR CONDITIONING EQUIPMENT & SUPPLIES","HEATING & AIR CONDITIONING SERVICE & REPAIR","HEATING & VENTILATING CONTRACTORS","HEATING CONTRACTORS","HEATING EQUIPMENT & SYSTEMS CLEANING & REPAIR","HEATING EQUIPMENT & SYSTEMS DEALERS","HEAVY CONSTRUCTION","HOME & BUILDING INSPECTION","HOME BUILDERS & DEVELOPERS","HOME HEALTH CARE","HOME IMPROVEMENT & MAINTENANCE","HVAC ENGINEERS","INDUSTRIAL & CONSTRUCTION FASTENERS","INDUSTRIAL CONTRACTORS","INSPECTION SERVICES","INSULATION CONTRACTORS","KITCHEN & BATHROOM REMODELING","KITCHEN CABINETS & EQUIPMENT DEALERS","KITCHEN DESIGN & REMODELING SERVICES","LAND CLEARING & LEVELING CONTRACTORS","LAND DRAINAGE CONTRACTORS","LANDSCAPE ARCHITECTS","LANDSCAPE CONTRACTORS","LANDSCAPE DESIGNERS & CONSULTANTS","LANDSCAPE SERVICES","LICENSED PLUMBING CONTRACTORS","LIGHTING CONSULTANTS & DESIGNERS","LIGHTING FIXTURES REPAIR MAINTENANCE & INSTALLATION","LIGHTING FIXTURES RETAIL","LOG HOMES BUILDINGS & CABINS DEALERS","MARINE CONTRACTORS & DESIGNERS","MASONRY CONTRACTORS","MASONRY EQUIPMENT & SUPPLIES","MECHANICAL CONTRACTORS","METAL BUILDINGS DEALERS","MIRRORS RETAIL","MOBILE HOME PARKS DEVELOPMENT & CONSTRUCTION","MOBILE HOME SERVICE REPAIR & IMPROVEMENTS","NATURAL & CUT STONE DEALERS","NATURAL GRANITE & MARBLE","OVERHEAD DOORS","PAINT REMOVAL & STRIPPING","PAINT STORES","PAINTING CONTRACTORS","PAINTING CONTRACTORS COMMERCIAL & INDUSTRIAL","PATIO PORCH DECK & GAZEBO BUILDERS","PAVEMENT & PARKING AREA MAINTENANCE & MARKING","PAVING CONTRACTORS","PIPELINE CONTRACTORS","PLASTERING CONTRACTORS","PLATE GLASS WINDOWS","PLUMBING & HEATING CONTRACTORS","PLUMBING CONTRACTORS","PLUMBING CONTRACTORS COMMERCIAL & INDUSTRIAL","PLUMBING EQUIPMENT & SUPPLIES WHOLESALE & MANUFACTURERS","PLUMBING EQUIPMENT PARTS & SUPPLIES","PLUMBING FIXTURES","PLUMBING SERVICE & REPAIR","PORTABLE BUILDINGS","PORTABLE TOILETS","PREFABRICATED & MODULAR BUILDINGS","RADON TESTING & MITIGATION","RAILINGS","READY-MIXED CONCRETE","REFRIGERATING SERVICE & REPAIR","REFRIGERATION DEALERS COMMERCIAL & INDUSTRIAL","REFRIGERATION PARTS & SUPPLIES","REFRIGERATOR & FREEZER PARTS & SUPPLIES DEALERS","RETAINING WALLS CONTRACTORS","ROAD & HIGHWAY CONTRACTORS","ROCK & STONE DEALERS","ROOFING","ROOFING CONSULTANTS","ROOFING CONTRACTORS","ROOFING CONTRACTORS COMMERCIAL & INDUSTRIAL","ROOFING MAINTENANCE & REPAIR","ROOFING MATERIALS DEALERS","ROOFING SERVICE & CONSULTANTS COMMERCIAL & INDUSTRIAL","ROOM ADDITIONS","SALVAGE YARDS","SAND & GRAVEL DEALERS","SCAFFOLDING & AERIAL LIFTS PARTS & SUPPLIES","SEPTIC TANK CLEANING & PUMPING","SEPTIC TANKS & SYSTEMS CONTRACTORS & DEALERS","SEPTIC TANKS & SYSTEMS INSTALLATION & REPAIR","SEWAGE BACKUP CLEANING SERVICES","SEWER & DRAIN CLEANING CONTRACTORS","SEWER & DRAIN CLEANING SERVICE & REPAIR","SEWER CONSTRUCTION CONTRACTORS","SEWER LINE INSPECTION & MAINTENANCE","SHEET METAL CONTRACTORS","SIDING CONTRACTORS","SIDING MATERIAL DEALERS","SOLAR ENERGY CONTRACTORS","SPECIAL TRADES CONTRACTORS","STEEL DISTRIBUTORS & SERVICE CENTERS","STEEL FABRICATION","STEEL FABRICATORS & ERECTORS","STORAGE SHEDS & BUILDINGS","STORAGE TRAILERS & CONTAINERS","STRUCTURAL STEEL","STRUCTURAL STEEL CONTRACTORS","STUCCO & COATING CONTRACTORS","SUN ROOMS GREENHOUSES SOLARIUMS & ATRIUMS BUILDERS","SWIMMING POOL & SPA CONSTRUCTION & CONTRACTORS","SWIMMING POOL COPING PLASTERING & TILING","SWIMMING POOLS SERVICE & REPAIR COMMERCIAL & INDUSTRIAL","TELECOMMUNICATIONS CONTRACTORS","TELEPHONE & TELEVISION CABLE CONTRACTORS","TERRAZZO MARBLE & TILE CONTRACTORS","TILE DEALERS","TILES CONTRACTORS","TILES REFINISHING CLEANING & REPAIR","TOOL RENTAL & LEASING","TOOLS REPAIR & PARTS","TREE & STUMP REMOVAL SERVICES","USED CONTRACTORS\" EQUIPMENT & SUPPLIES","UTILITIES CONTRACTORS","VENTILATING SYSTEMS CLEANING","WALLPAPER & WALLCOVERINGS CONTRACTORS","WATER & SEWAGE COMPANIES","WATER HEATERS","WATER WELL DRILLING & SERVICE","WATERPROOFING CONTRACTORS","WINDOW CONTRACTORS","WINDOW COVERINGS INSTALLATION CLEANING & REPAIR","WINDOW GLASS COATING & TINTING","WINDOW INSTALLATION","WINDOW REPAIR & REPLACEMENT","WOOD & LAMINATE FLOORING","WOODWORKING","WRECKING & DEMOLITION CONTRACTORS","ACADEMIC SPECIALTY SCHOOLS","ADULT & CONTINUING EDUCATION","AFTER SCHOOL PROGRAMS","AVIATION SCHOOLS","BARBER & BEAUTY SCHOOLS","BUSINESS & PERSONAL COACHING","BUSINESS EDUCATION","CAREER & VOCATIONAL COUNSELING","CATHOLIC SCHOOLS","CHILD DEVELOPMENT CENTERS","CHRISTIAN SCHOOLS","COLLEGES & UNIVERSITIES","COMPUTER TRAINING","CRAFTS INSTRUCTION & SCHOOLS","DEFENSIVE DRIVING INSTRUCTION","EDUCATIONAL ADMINISTRATION","EDUCATIONAL CONSULTANTS","EDUCATIONAL ORGANIZATIONS","EDUCATIONAL SERVICES","ELEMENTARY & SECONDARY EDUCATION","ELEMENTARY SCHOOLS","HIGH SCHOOLS","INDUSTRIAL & TRADE SCHOOLS","JUNIOR COLLEGES & TECHNICAL INSTITUTES","JUNIOR HIGH & MIDDLE SCHOOLS","LANGUAGE SCHOOLS & INSTRUCTION","LEARNING CENTERS","MEDICAL SCHOOLS","MONTESSORI SCHOOLS","MUSIC INSTRUCTION","PRESCHOOLS & KINDERGARTENS","PRIVATE SCHOOLS","PUBLIC SCHOOLS","READING IMPROVEMENT INSTRUCTION","RELIGIOUS EDUCATION SCHOOLS","SCHOOLS","SELF DEFENSE SCHOOLS & PROGRAMS","SPORTS & FITNESS INSTRUCTION","TEST PREPARATION & TUTORING SERVICES","TRAINING PROGRAMS & SERVICES","VOCAL MUSIC INSTRUCTION","VOCATIONAL EDUCATION","AMERICAN RESTAURANTS","ASIAN RESTAURANTS","BAGEL SHOPS","BAKED GOODS WHOLESALE & MANUFACTURERS","BAKERIES","BAR & GRILL RESTAURANTS","BARBECUE RESTAURANTS","BARS & PUBS","BEER & ALE RETAIL","BEVERAGES RETAIL","BISTROS","BREAKFAST & BRUNCH RESTAURANTS","BREWERIES","BUFFETS RESTAURANTS","BURGER RESTAURANTS","BUTCHERS","CAFES","CAFETERIAS","CAJUN & CREOLE RESTAURANTS","CAKE & PIE SHOPS","CANDY & CONFECTIONERY RETAIL","CARIBBEAN RESTAURANTS","CATERERS","CHICKEN RESTAURANTS","CHICKEN TAKE OUT","CHINESE RESTAURANTS","COFFEE & TEA SHOPS","COFFEE RETAIL","CONDIMENTS & SAUCES RETAIL","CONVENIENCE STORE DELICATESSENS","COOKIES & CRACKERS RETAIL","DAIRY STORES","DELICATESSENS","DESSERT RESTAURANTS","DONUT SHOPS","FAMILY RESTAURANTS","FARMERS\" MARKETS","FAST FOOD RESTAURANTS","FINE DINING RESTAURANTS","FISH & SEAFOOD RETAIL","FISH & SEAFOOD WHOLESALE","FOOD & BEVERAGE DELIVERY SERVICES","FOOD & BEVERAGE SERVICES","FOOD PRODUCTS RETAIL","FOOD PRODUCTS WHOLESALE & MANUFACTURERS","FRENCH RESTAURANTS","GLUTEN-FREE FOODS","GREEK RESTAURANTS","GROCERY STORES & SUPERMARKETS","HEALTH & DIET FOODS RETAIL","HOME COOKING RESTAURANTS","HOT DOG RESTAURANTS","ICE CREAM & FROZEN YOGURT SHOPS","INDIAN RESTAURANTS","ITALIAN FOODS","ITALIAN RESTAURANTS","JAPANESE RESTAURANTS","JUICE BARS","LATE NIGHT DINING RESTAURANTS","LATIN AMERICAN RESTAURANTS","LIQUOR STORES","LUNCH RESTAURANTS","MEAL PREPARATION","MEATS","MEATS RETAIL","MEDITERRANEAN RESTAURANTS","MEXICAN FOODS","MEXICAN RESTAURANTS","NIGHTCLUBS","ORGANIC FOODS & PRODUCTS","ORIENTAL RESTAURANTS","PANCAKES & WAFFLES RESTAURANTS","PASTA RESTAURANTS","PIZZA DELIVERY","PIZZA RESTAURANTS","PRETZELS","PUBS","RESTAURANT EQUIPMENT & SUPPLIES WHOLESALE & MANUFACTURERS","RESTAURANTS","SALADS","SANDWICH SHOPS","SEAFOOD RESTAURANTS","SNACK FOODS RETAIL","SOUTHERN STYLE RESTAURANTS"};
				
				//LoadLinkByCityStateService loadLinkByCityStateService = (LoadLinkByCityStateService) context.getBean("loadLinkByCityService");				
				//loadLinkByCityStateService.load(city, state, categories);
				
				logger.info("Job Launching " + jobName + " quota[1000] lastProcessedKey[0]");
				JobLauncher jobLauncher = (JobLauncher) context.getBean("jobLauncher");
				Job job = (Job) context.getBean("simpleYellowpagesJob");

				try {
					
					JobParametersBuilder builder = new JobParametersBuilder();
					builder.addString("quota", "11205");
					builder.addString("lastProcessedKey", "0");
					builder.addString("jobName", "simpleYellowpagesJob");
					
					JobExecution execution = jobLauncher.run(job, builder.toJobParameters());
					
					if(execution.getAllFailureExceptions().size() > 0) {
						for(Throwable t : execution.getAllFailureExceptions()) {
							t.printStackTrace();
						}
					}else {
						logger.info("No exeptions found");
					}

					logger.info("Exit Status : " + execution.getStatus());
					
					if(execution.getStatus() == BatchStatus.FAILED) {
						logger.error("Batch job failed");
						System.exit(1);
					}else {
						logger.info("Batch job successful");
						System.exit(0);
					}
				} catch (Exception e) {
					logger.info("Error : " + e.getMessage());
					e.printStackTrace();
					System.exit(1);
				}

				System.exit(0);
			}
			
			
			/**
			 * **********
			 * FINISH DOING ONE OFF JOB
			 */

			String selectMaxId = props.getProperty("cron.job.select.max.job.id");
			String selectDataProcessingJob = props.getProperty("cron.job.select.data.processing.job");
			
			logger.info(selectMaxId);
			logger.info(selectDataProcessingJob);
			
			if("crawlerSiteMapJob".equals(jobName) || "storeDataUpdateJob".equals(jobName)) {
				JdbcTemplate cronJdbcTemplate = (JdbcTemplate) context.getBean("jdbcTemplate");
				String categoryQuery = props.getProperty("cron.job.sitemap.category.query");
				Map<Integer, List<String>> categories = (Map<Integer, List<String>>) context.getBean("categories");
				
				/*
				 * get map of category id to category name
				 */
				cronJdbcTemplate.query(categoryQuery, (rs, rowNum) -> {
					KeyValuePair<Integer, String> pair = new KeyValuePair<Integer, String>();
					pair.setKey(rs.getInt("_category_id"));
					pair.setValue(rs.getString("name").toLowerCase().replaceAll("[\\s|\\W]+", "-"));
					return pair;
				})
				.stream()
				.forEach(pair -> {
					List<String> names = categories.get(pair.getKey());
					if(names == null) {
						names = new ArrayList<String>();
					}
					names.add(pair.getValue());
					categories.put(pair.getKey(), names);
				});

				logger.debug("categories size " + categories.size());
				for(Map.Entry<Integer, List<String>> entry : categories.entrySet()) { 
					logger.debug("categoryid " + entry.getKey() + " category names size " + entry.getValue().size());
				}
			}
			
			
			if("yellowpagesDataJob".equals(jobName) || "yelpDataJob".equals(jobName)) {
				if(args.length < 5) {
					logger.error("Business data job requires 5 arguments.");
					System.out.println("Exit Code 1");
					System.exit(1);
				}
			
				JdbcTemplate cronJdbcTemplate = (JdbcTemplate) context.getBean("jdbcTemplate");
				String categoryQuery = props.getProperty("cron.job.sitemap.category.query");

				Map<Integer, Integer> categoryLevel2Mapping = (Map<Integer, Integer>) context.getBean("categoryLevel2Mapping");

				/*
				 * get map of category id to category name
				 */
				cronJdbcTemplate.query(categoryQuery, (rs, rowNum) -> {
					KeyValuePair<Integer, Integer> pair = new KeyValuePair<Integer, Integer>();
					pair.setKey(rs.getInt("id"));
					pair.setValue(rs.getInt("_category_id"));
					return pair;
				})
				.stream()
				.forEach(pair -> categoryLevel2Mapping.put(pair.getKey(), pair.getValue()));

				logger.debug("categories size " + categoryLevel2Mapping.size());
				for(Map.Entry<Integer, Integer> entry : categoryLevel2Mapping.entrySet()) { 
					logger.debug("categoryid " + entry.getKey() + " category names size " + entry.getValue());
				}
			}
			
			List<DataProcessingCrons> crons = null;
			try {
				Integer maxId = jdbcTemplate.queryForObject(selectMaxId, new Object[]{jobName}, Integer.class);
				crons = jdbcTemplate.query(selectDataProcessingJob, new Object[]{maxId}, new DataProcessingCronsMapper());
			} catch(Exception e) {
				logger.warn("Unable to retrieve job");
				System.exit(0);
			}
			
			if(crons != null && !crons.isEmpty()) {
				logger.info("Job Launching " + jobName + " quota["+crons.get(0).getQuota()+"] lastProcessedKey[" + crons.get(0).getLastProcessedKey() + "]");
				JobLauncher jobLauncher = (JobLauncher) context.getBean("jobLauncher");
				Job job = (Job) context.getBean(jobName);

				try {
					
					JobParametersBuilder builder = new JobParametersBuilder();
					builder.addString("quota", crons.get(0).getQuota() + "");
					builder.addString("lastProcessedKey", crons.get(0).getLastProcessedKey() + "");
					builder.addString("jobName", jobName);
					
					
					if("yellowpagesDataJob".equals(jobName) || "yelpDataJob".equals(jobName)) {
						String city = args[3].split("=")[1];
						String state = args[4].split("=")[1];
						
					
					
						builder.addString("city", city);
						builder.addString("state", state);
					}
					
					
					
					JobExecution execution = jobLauncher.run(job, builder.toJobParameters());
					
					if(execution.getAllFailureExceptions().size() > 0) {
						for(Throwable t : execution.getAllFailureExceptions()) {
							t.printStackTrace();
						}
					}else {
						logger.info("No exeptions found");
					}

					logger.info("Exit Status : " + execution.getStatus());
					
					if(execution.getStatus() == BatchStatus.FAILED) {
						logger.error("Batch job failed");
						System.exit(1);
					}else {
						logger.info("Batch job successful");
						System.exit(0);
					}
				} catch (Exception e) {
					logger.info("Error : " + e.getMessage());
					e.printStackTrace();
				}
			}
			logger.info("End of Job " + jobName);
		} catch (Exception e1) {
			logger.info("Error : " + e1.getMessage());
			e1.printStackTrace();
		}
		
		System.exit(1);
	}
}
